---
title: "STA 325 Project"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(e1071)
library(tidyverse)
library(randomForest)
library(tree)
```

```{r}
UFC <- read.csv("data/preprocessed_data.csv")
```

```{r preprocessing}
UFC.new <- UFC %>% 
  mutate(R_win_percent = R_wins/(R_wins + R_losses + R_draw),
         B_win_percent = B_wins/(B_wins + B_losses + B_draw),
         R_win_percent = ifelse(is.na(R_win_percent), 0, R_win_percent),
         B_win_percent = ifelse(is.na(B_win_percent), 0, B_win_percent),
         win = ifelse(Winner == "Red", 1, 0),
         longest_win_streak_dif = R_longest_win_streak - B_longest_win_streak,
         winperc_dif = R_win_percent - B_win_percent,
         height_dif = R_Height_cms - B_Height_cms,
         reach_dif = R_Reach_cms - B_Reach_cms,
         weight_dif = R_Weight_lbs - B_Weight_lbs,
         age_dif = R_age - B_age,
         avg_KD_dif = R_avg_KD - B_avg_KD,
         avg_opp_KD_dif = R_avg_opp_KD - B_avg_opp_KD,
         avg_SIG_STR_pct_dif = R_avg_SIG_STR_pct - B_avg_SIG_STR_pct,
         avg_opp_SIG_STR_pct_dif = R_avg_opp_SIG_STR_pct - B_avg_opp_SIG_STR_pct,
         avg_TD_pct_dif = R_avg_TD_pct - B_avg_TD_pct,
         avg_opp_TD_pct_dif = R_avg_opp_TD_pct - B_avg_opp_TD_pct,
         avg_SUB_ATT_dif = R_avg_SUB_ATT - B_avg_SUB_ATT,
         avg_opp_SUB_ATT_dif = R_avg_opp_SUB_ATT - B_avg_opp_SUB_ATT,
         avg_REV_dif = R_avg_REV - B_avg_REV,
         avg_opp_REV_dif = R_avg_opp_REV - B_avg_opp_REV,
         avg_SIG_STR_att_dif = R_avg_SIG_STR_att - B_avg_SIG_STR_att,
         avg_SIG_STR_landed_dif = R_avg_SIG_STR_landed - B_avg_SIG_STR_landed,
         avg_opp_SIG_STR_att_dif = R_avg_opp_SIG_STR_att - B_avg_opp_SIG_STR_att,
         avg_opp_SIG_STR_landed_dif = R_avg_opp_SIG_STR_landed - B_avg_opp_SIG_STR_landed,
         avg_TOTAL_STR_att_dif = R_avg_TOTAL_STR_att - B_avg_TOTAL_STR_att,
         avg_TOTAL_STR_landed_dif = R_avg_TOTAL_STR_landed - B_avg_TOTAL_STR_landed,
         avg_opp_TOTAL_STR_att_dif = R_avg_opp_TOTAL_STR_att - B_avg_opp_TOTAL_STR_att,
         avg_opp_TOTAL_STR_landed_dif = R_avg_opp_TOTAL_STR_landed - B_avg_opp_TOTAL_STR_landed,
         avg_TD_att_dif = R_avg_TD_att - B_avg_TD_att,
         avg_TD_landed_dif = R_avg_TD_landed - B_avg_TD_landed, 
         avg_opp_TD_att_dif = R_avg_opp_TD_att - B_avg_opp_TD_att,
         avg_opp_TD_landed_dif = R_avg_opp_TD_landed - B_avg_opp_TD_landed,
        avg_HEAD_att_dif = R_avg_HEAD_att - B_avg_HEAD_att,
        avg_HEAD_landed_dif = R_avg_HEAD_landed - B_avg_HEAD_landed,
        avg_opp_HEAD_att_dif = R_avg_opp_HEAD_att - B_avg_opp_HEAD_att,
        avg_opp_HEAD_landed_dif = R_avg_opp_HEAD_landed - B_avg_opp_HEAD_landed,
        avg_BODY_att_dif = R_avg_BODY_att - B_avg_BODY_att,
        avg_BODY_landed_dif = R_avg_BODY_landed - B_avg_BODY_landed,
        avg_opp_BODY_att_dif = R_avg_opp_BODY_att - B_avg_opp_BODY_att,
        avg_opp_BODY_landed_dif = R_avg_opp_BODY_landed - B_avg_opp_BODY_landed,
        avg_LEG_att_dif = R_avg_LEG_att - B_avg_LEG_att,
        avg_LEG_landed_dif = R_avg_LEG_landed - B_avg_LEG_landed,
        avg_opp_LEG_att_dif = R_avg_opp_LEG_att - B_avg_opp_LEG_att,
        avg_opp_TD_att_dif = R_avg_opp_TD_att - B_avg_opp_TD_att,
        avg_opp_LEG_landed_dif = R_avg_opp_LEG_landed - B_avg_opp_LEG_landed,
        avg_DISTANCE_att_dif = R_avg_DISTANCE_att - B_avg_DISTANCE_att,
        avg_DISTANCE_landed_dif = R_avg_DISTANCE_landed - B_avg_DISTANCE_landed,
        avg_opp_DISTANCE_att_dif = R_avg_opp_DISTANCE_att - B_avg_opp_DISTANCE_att,
        avg_opp_DISTANCE_landed_dif = R_avg_opp_DISTANCE_landed - B_avg_opp_DISTANCE_landed,
        avg_CLINCH_att_dif = R_avg_CLINCH_att - B_avg_CLINCH_att,
        avg_CLINCH_landed_dif = R_avg_CLINCH_landed - B_avg_CLINCH_landed,
        avg_opp_CLINCH_att_dif = R_avg_opp_CLINCH_att - B_avg_opp_CLINCH_att,
        avg_opp_CLINCH_landed_dif = R_avg_opp_CLINCH_landed - B_avg_opp_CLINCH_landed,
        avg_GROUND_att_dif = R_avg_GROUND_att - B_avg_GROUND_att,
        avg_GROUND_landed_dif = R_avg_GROUND_landed - B_avg_GROUND_landed,
        avg_opp_GROUND_att_dif = R_avg_opp_GROUND_att - B_avg_opp_GROUND_att,
         avg_opp_GROUND_landed_dif = R_avg_opp_GROUND_landed - B_avg_opp_GROUND_landed,
         avg_CTRL_time.seconds._dif = R_avg_CTRL_time.seconds. - B_avg_CTRL_time.seconds. ,
         avg_opp_CTRL_time.seconds._dif = R_avg_opp_CTRL_time.seconds. - B_avg_opp_CTRL_time.seconds. ,
         total_time_fought.seconds._dif = R_total_time_fought.seconds. - B_total_time_fought.seconds. ,
         total_rounds_fought_dif = R_total_rounds_fought - B_total_rounds_fought,
         total_title_bouts_dif = R_total_title_bouts - B_total_title_bouts,
         current_lose_streak_dif = R_current_lose_streak - B_current_lose_streak,
         current_win_streak_dif = R_current_win_streak - B_current_win_streak,
         losses_dif = R_losses - B_losses,
         draw_dif = R_draw - B_draw,
         win_by_Decision_Majority_dif = R_win_by_Decision_Majority - B_win_by_Decision_Majority,
         win_by_Decision_Split_dif = R_win_by_Decision_Split - B_win_by_Decision_Split,
         win_by_Decision_Unanimous_dif =  R_win_by_Decision_Unanimous - B_win_by_Decision_Unanimous,
         win_by_KO.TKO_dif = R_win_by_KO.TKO - B_win_by_KO.TKO,
         win_by_Submission_dif = R_win_by_Submission - B_win_by_Submission,
         win_by_TKO_Doctor_Stoppage_dif = R_win_by_TKO_Doctor_Stoppage - B_win_by_TKO_Doctor_Stoppage,
        R_stance = ifelse(R_Stance_Open.Stance == 1, "Open",
                           ifelse(R_Stance_Orthodox == 1, "Orthodox",
                                  ifelse(R_Stance_Sideways == 1, "Sideways",
                                         ifelse(R_Stance_Southpaw == 1, "Southpaw",
                                                ifelse(R_Stance_Switch == 1, "Switch", "None"))))),
        B_stance = ifelse(B_Stance_Open.Stance == 1, "Open",
                           ifelse(B_Stance_Orthodox == 1, "Orthodox",
                                  ifelse(B_Stance_Sideways == 1, "Sideways",
                                         ifelse(B_Stance_Southpaw == 1, "Southpaw",
                                                ifelse(B_Stance_Switch == 1, "Switch", "None"))))),
        weightclass = ifelse(weight_class_Bantamweight == 1, "Bantam",
                              ifelse(weight_class_CatchWeight == 1, "Catch",
                                     ifelse(weight_class_Featherweight == 1, "Feather",
                                            ifelse(weight_class_Flyweight == 1, "Fly",
                                                   ifelse(weight_class_Heavyweight == 1, "Heavy",
                                                          ifelse(weight_class_LightHeavyweight == 1, "Light Heavy",
                                                                 ifelse(weight_class_Lightweight == 1, "Light",
                                                                        ifelse(weight_class_Middleweight == 1, "Middle",
                                                                               ifelse(weight_class_OpenWeight == 1, "Open",
                                                                                      ifelse(weight_class_Welterweight == 1, "Welter",
                                                                                             ifelse(weight_class_WomenBantamweight == 1, "Women Bantam",
                                                                                                    ifelse(weight_class_WomenFeatherweight == 1, "Women Featherweight",
                                                                                                           ifelse(weight_class_WomenFlyweight == 1, "Women Flyweight",
                                                                                                                  ifelse(weight_class_WomenStrawweight == 1, "Women Strawweight", "None"))))))))))))))
        )
UFC.new <- UFC.new %>%
  dplyr::select(-c(R_win_percent, B_win_percent, losses_dif, draw_dif))
UFC.new <- UFC.new %>%
  mutate(R_stance = as.factor(R_stance),
         B_stance = as.factor(B_stance),
         weightclass = as.factor(weightclass))
UFC.new <- UFC.new[161:229]

UFC.new <- UFC.new %>%
  mutate(win = as.factor(win))
```

```{r}
UFC.new %>%
  head(10)
```

```{r}
ggplot(data = UFC.new, aes(x = win, y = age_dif, fill = win)) + 
  geom_boxplot(alpha=0.6, outlier.shape = NA) + 
  scale_y_continuous(limits = c(-15, 16)) + 
  labs(x = "Did Red Win?(1 corresponds to yes, 0 corresponds to no)",
       y = "Age Differential(Red - Blue)",
       title = "Red Winning Skewed Towards Lower Ages") +
  scale_fill_manual(values=c("blue", "red")) + 
  stat_summary(fun = mean, geom="point", shape = 20, size = 5, color="white", fill="white") +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none")
```

```{r}
plot2 <- UFC.new %>% 
  group_by(R_stance) %>% 
  count(win == 1) %>% 
  mutate(totalperstance = sum(n)) %>% 
  mutate(percentwinbystance = n/totalperstance)
names(plot2)<-str_replace_all(names(plot2), c(" " = ".", "=" = ""))
plot2sel <- plot2 %>% 
  filter(win..1 == TRUE) %>% 
  dplyr::select(R_stance, percentwinbystance)
ggplot(data = plot2sel, aes(x = R_stance, y = percentwinbystance, fill = R_stance)) + 
  geom_col(alpha=0.6) + 
  labs(x = "Fighter R's Stance",
       y = "Percentage of Fights Where R Won",
       title = "Small Difference in Win Percentage for Each Stance",
       subtitle = "Small Sample Sizes for Open and Sideways Variables") +
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(plot.subtitle = element_text(hjust = 0.5), legend.position = "none")
```

```{r}
ggplot(data = UFC.new, aes(x = win, y = avg_TOTAL_STR_att_dif, fill = win)) + 
  geom_boxplot(alpha=0.6, outlier.shape = NA) + 
  scale_y_continuous(limits = c(-50, 50)) + 
  labs(x = "Did Red Win?(1 corresponds to yes, 0 corresponds to no)",
       y = "Difference in Number of Average Total Strikes Attempted",
       title = "Red Wins a Little More Often When ") +
  stat_summary(fun = mean, geom="point", shape = 20, size = 5, color="white", fill="white") +
  scale_fill_manual(values=c("blue", "red")) + 
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none",
        plot.subtitle = element_text(hjust = 0.5))
```

# Cross Validation for Top x (1 <= x <= 40) Predictor Variables

## Logistic Regression

```{r}
library(broom)
library(sjmisc)
```

```{r}
set.seed(123)
smp_size <- floor(0.8 * nrow(UFC.new))
train_ind <- sample(seq_len(nrow(UFC.new)), size = smp_size)
train <- UFC.new[train_ind, ]
test <- UFC.new[-train_ind, ]
```

```{r}
lmfit <- glm(win ~ ., data = train, family="binomial")
coefs <- tidy(lmfit)
vars <- coefs[order(coefs$p.value),]$term
l <- length(vars)
for (i in 1:l) {
  cont <- str_contains(vars[i],"weightclass")
  cont2 <- str_contains(vars[i], "R_stance")
  cont3 <- str_contains(vars[i], "B_stance")
  if (cont) {
    vars[i] = "weightclass"
  }
  if (cont2) {
    vars[i] = "R_stance"
  }
  
  if (cont3) {
    vars[i] = "B_stance"
  }
  
}
vars
```


```{r}
logistic_cross_val <- function(vars, min_preds, max_preds)
{
  for(i in min_preds:max_preds)
  {
    predictors <- paste(vars[1:i], collapse=" + ")
    lmfit <- glm(as.formula(paste("win", predictors, sep=" ~ ")), data = train, family="binomial")
    pred <- predict(lmfit, test, type = "response")
    ypred <- ifelse(pred > 0.5, 1, 0)
    accuracy <- length(ypred[test$win==ypred]) / length(ypred)
    print(sprintf("predictors: %s", predictors))
    print(sprintf("Test prediction accuracy: %f", accuracy))
    print(" ")
  }
}
```

```{r}
logistic_cross_val(vars, 1, 47)
```

```{r}
length(test$win[test$win==1]) / length(test$win)
```

## SVMs


```{r}
UFC.num <- UFC.new %>%
  select(-c(B_stance, R_stance, weightclass, win))
```


```{r}
set.seed(123)
smp_size <- floor(0.8 * nrow(UFC.num))
train_ind <- sample(seq_len(nrow(UFC.num)), size = smp_size)
train_num <- UFC.num[train_ind, ]
test_num <- UFC.num[-train_ind, ]
```

```{r}
print("proportion of red wins (naive red predict test accuracy)")
length(test$win[test$win==1]) / length(test$win)
```

```{r}
svm_cross_val <- function(vars, min_preds, max_preds)
{
  for(i in min_preds:max_preds)
  {
    pca_train <- prcomp(train_num, center = TRUE, scale. = TRUE, )
    
    train_components <- as.data.frame(cbind(win = as.numeric(train$win) - 1, pca_train$x[, 1:i]))
    
    svmfit <- svm(win ~ ., data = train_components, family = "binomial", kernel = "linear",
                  cost = 10, scale=TRUE)
    
    pca_test <- prcomp(test_num, center = TRUE, scale. = TRUE)
    test_components <- as.data.frame(cbind(win = as.numeric(test$win) - 1, pca_test$x[, 1:i]))
    pred <- predict(svmfit, test_components, type = "response")
    ypred <- ifelse(pred > 0.5, 1, 0)
    accuracy <- length(ypred[test$win==ypred]) / length(ypred)
    print(sprintf("Num predictors: %d", i))
    print(sprintf("Test prediction accuracy: %f", accuracy))
    print(" ")
  }
}
```

```{r}
svm_cross_val(vars, 2, 26)
```



## Trees


```{r}
tree.UFC <- tree(as.factor(win) ~ ., data = train)
tree.pred <- predict(tree.UFC, newdata = test, type = "class")
table(tree.pred, test$win)
sum(diag(table(tree.pred, test$win)))/(1182+589)
```

```{r}
set.seed(3)
cv.UFC <- cv.tree(tree.UFC, FUN = prune.misclass)
names(cv.UFC)
cv.UFC
```

```{r}
par(mfrow = c(1,2))
plot(cv.UFC$size, cv.UFC$dev, type = "b")
plot(cv.UFC$k, cv.UFC$dev, type = "b")
```

```{r}
prune.UFC <- prune.misclass(tree.UFC, best = 2)
plot(prune.UFC)
text(prune.UFC, pretty = 0)
```


# Final Model

```{r}
lmfit <- glm(win ~ age_dif + reach_dif + avg_opp_CTRL_time.seconds._dif + weightclass + avg_TD_att_dif + height_dif + avg_SIG_STR_pct_dif + total_time_fought.seconds._dif + avg_TOTAL_STR_att_dif + avg_DISTANCE_att_dif + avg_TOTAL_STR_landed_dif + avg_CTRL_time.seconds._dif + avg_opp_BODY_landed_dif + win_by_Decision_Split_dif + avg_opp_BODY_att_dif + avg_DISTANCE_landed_dif + avg_SIG_STR_landed_dif + avg_BODY_landed_dif + avg_HEAD_landed_dif + avg_LEG_landed_dif + avg_SIG_STR_att_dif + avg_BODY_att_dif + avg_SUB_ATT_dif + avg_HEAD_att_dif + avg_LEG_att_dif + avg_opp_TD_pct_dif + avg_opp_CLINCH_att_dif + avg_opp_KD_dif + winperc_dif + avg_opp_SIG_STR_pct_dif + avg_opp_TD_landed_dif + longest_win_streak_dif + avg_opp_CLINCH_landed_dif + avg_opp_SIG_STR_att_dif + avg_opp_HEAD_att_dif + avg_opp_HEAD_landed_dif, data = train, family="binomial")
```

```{r}
summary(lmfit)
```


```{r}
pred <- predict(lmfit, test, type = "response")
    ypred <- ifelse(pred > 0.5, 1, 0)
    accuracy <- length(ypred[test$win==ypred]) / length(ypred)
    print(sprintf("predictors: %s", predictors))
    print(sprintf("Test prediction accuracy: %f", accuracy))
    print(" ")
```

# Model Diagnostics

```{r}
car::vif(lmfit)
```


```{r}
table(ypred, test$win)
```

```{r}
plot(lmfit, which = 4, id.n = 3)

# Extract model results
lmfit.data <- augment(lmfit) %>% 
  mutate(index = 1:n())

lmfit.data %>% top_n(3, .cooksd)

ggplot(lmfit.data, aes(index, .std.resid)) + 
  geom_point(aes(color = win), alpha = .5) +
  theme_bw()
```

```{r}
pred <- predict(lmfit, test, type = "response")
    ypred <- ifelse(pred > 0.5, 1, 0)
    accuracy <- length(ypred[test$win==ypred]) / length(ypred)
    #print(sprintf("predictors: %s", predictors))
    print(sprintf("Test prediction accuracy: %f", accuracy))
    print(" ")
```

# ROC Curve

```{r}
library(pROC)
test_prob = predict(lmfit, newdata = test, type = "response")
test_roc = roc(test$win ~ test_prob, plot = TRUE, print.auc = TRUE)
```
